### ISSUE TITLE
Week day printing only 5 for every week day.

### ISSUE THREAD

**Issue by Tesfamichael1074** [Nabute/Abushakir#7]
I used a simple print statement to print out one of the days in a week as its numerical representation but it printed out "5" which is incorrect because I tried it on Monday. I also tried to subtract some days from the etdatetime object but still it printed out "5".

**Comment by Nabute** [comment]
Can you provide sample code?

**Comment by Nabute** [comment]
as of the documentation the [weekday getter](https://pub.dev/documentation/abushakir/latest/abushakir/EtDatetime/weekday.html) will return the first day of the month of the EtDatetime instance. So to get the weekday of anyday in that month, you need to do...
```dart
EtDatetime now = new EtDatetime.now()  // 2012/09/24
int monthFirstWeekDay = now.weekday // => 5, means ቅዳሜ (weekday the 9th month of 2012 starts)
```
to get any weekday of any date, for instance 24 in our case, we will add 24 to 5 and subtract 1 and finally get the remainder by dividing for 7.

```dart
int ourWeekday = (( 24 + 5) - 1) % 7 // => 0 means ሰኞ, since weekdays start from ሰኞ
```

**Comment by Tesfamichael1074** [comment]
Thanks man. It even simplified my work.

**Comment by Nabute** [comment]
My Pleasure.
